### ISSUE TITLE
Idea for clarity for folks unfamiliar with p-s

### ISSUE THREAD

**Issue by DavidWells** [kentcdodds/p-s#1]
Kent love this idea!

One issue that I have seen by all of the 'better npm scripts' setups is new folks not grokking what exactly the abstraction is doing or what it is running. 

A.k.a the "p-s... what in the..." reaction from people unaware of this package

Has a proposal to potentially help folks looking at the package.json 

before:
```json
{
  "scripts": {
    "start": "p-s"
  }
}
```

after:
```json
{
  "scripts": {
    "start": "p-s && echo 'Look in package-scripts.js for script information'"
  }
}
```

Just my 2 cents!

**Comment by kentcdodds** [comment]
Good point! Yet another  example of the fundamental problem with JSON's lack of comments! We cannot escape it!

What if we exposed the binary as `package-scripts` in addition to the existing `p-s`?

Feel free to file a pull request! Just an update to the `bin` in the `package.json` ought to do it!

**Comment by DavidWells** [comment]
sounds good. I will take a stab at it.
