### ISSUE TITLE
Proper handling and forwarding of `--flags`

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/p-s#100]
Right now you can do:

```console
nps foo --bar
```

And `p-s` will run the script called `foo` with the flag called `--bar`

However if you run:

```console
nps foo --silent --bar
```

then `p-s` will run the script called `foo` with the flag called `--bar` but without the flag called `--silent`. This is because of [this](https://github.com/kentcdodds/p-s/blob/3566a15b991d6b84e7386bd18b0e08c2e94c6235/src/bin-utils/index.js#L113-L124).

Normally it's not a huge deal. I think that's confusing.

Here are a few possible solutions (all of them are breaking):

1. Only accept `p-s` flags before the scripts (so you'd have to do `nps --silent foo --bar`)
2. Require `--` before the scripts and flags (`nps --silent -- foo --bar`)
3. Forward all flags whether they're `p-s` related or not (`nps foo --silent --bar` and forwards `--silent` and `--bar` both)

I can't think of a way to change this behavior without breaking things.

My favorite solution is the first. Mostly because it's least noisy and seems to make the most sense.

I'm working on #70 right now and will make this a part of that PR. I want feedback on this really quick. If anyone has any ideas let me know. If you'd like to vote for one or the other use github reactions to vote: :+1: for 1, :smile: for 2, :tada: for 3, and :confused: for "I don't know/care"

**Comment by gunnx** [comment]
👍

**Comment by kentcdodds** [comment]
Actually, yargs has a pretty sweet API for this. I think we'll do things in a way that's mostly backward compatible. If you want to forward flags into commands, you'll have to put those commands in quotes. This will make the most sense I think!

**Comment by addityasingh** [comment]
@kentcdodds But do you think it would look a clean syntax?
```javascript
nps 'build --foo'
```

My 2 cents: I would still prefer to not have any special syntax for my cli commands and below would be better than above:
```javascript
nps build --foo
```

**Comment by kentcdodds** [comment]
Yeah, I can see how the syntax looks much cleaner. As I described though, the problem is that there's no way to know whether the user intends for the command to be passed to `p-s` or `build`. Things get even more complicated when you have multiple scripts you're running too. Before we just forwarded all non-`p-s` flags on, but that got confusing if you wanted to pass on a flag to a script that `p-s` wouldn't forward (like `--silent`).

I think that this is a situation where explicit is better. Most of the time I expect that people don't pass flags via the command line directly and the flags happen inside the `package-scripts.js` file. So saving time typing is ok.

**Comment by kentcdodds** [comment]
Actually, I've been wrestling with this a lot because I actually realized that I pass flags/arguments to `nps` on the command line all the time. For example: `nps t file-to-test.js --no-cache` is something that I'll do fairly regularly. And I would get annoyed if I had to wrap that in quotes everytime.

So here's a proposal:

- Remove the ability to do multiple scripts in series with a single `nps` invocation (so no more `nps lint test build`, you'd have to do `nps lint && nps test && nps build`)
- force all `nps` argument to come before the script name: (so you can't do `nps lint --require babel-register --cache` you'd have to do `nps --require babel-register lint --cache`, otherwise `--require babel-register` would be forwarded onto the `lint` script in addition to `--cache`)

I'm not a huge fan of this either. I'm really unsure of what to do here because I don't want to make things confusing, but I want them to be ergonomic. Right now I think we favor economics to clear. Maybe we should just leave things as they are... 🤔

**Comment by kentcdodds** [comment]
I think we're just going to require the quotes. But I'm going to add option validation so if you try `nps build --foo` you'll get an error indicating that you may have forgotten to add quotes.

**Comment by addityasingh** [comment]
Even though I would have preferred no-quotes, but I see your point now. But adding the error for no quotes should definitely be more consistent 👍
