### ISSUE TITLE
support for pre

### ISSUE THREAD

**Issue by benmonro** [kentcdodds/p-s#106]
- `p-s` version:3.1.0
- `node` version:6
- `npm` version:4

Scripts file (or at least the relevant bits):

```javascript

```

The command executed:

```console

```

The output:

```console

```

Problem description:

currently there's no support for 'pre' scripts in nps.  it would be nice if p-s suppported this for when we import scripts from npm.

Suggested solution:

**Comment by kentcdodds** [comment]
Hi @benmonro,
Thanks for the issue. But we've discussed this and decided to not do it. You can follow the discussion in #67 and in the PR #83.
