### ISSUE TITLE
Preload module option

### ISSUE THREAD

**Issue by tim-mcgee** [kentcdodds/p-s#13]
How about a command line option similar to avas or tapes --require so you can have Babel, Coffescript or Typescript config files.

package.json
````json
"scripts": {
  "start": "package-scripts --require babel-register"
}
````

package-scripts.js
````javascript
export default {
  scripts: {
    build: 'webpack'
  }
}
````

command line
````
npm start build
````

**Comment by kentcdodds** [comment]
Yeah, that seems reasonable to me. I'm thinking that we could do something [here](https://github.com/kentcdodds/p-s/blob/bea8faab2bb0273220765780c6838a1f26195aa8/bin/p-s.js#L33):

```javascript
if (program.require) {
  require(program.require)
}
```

That should do it.

Would you be willing to [makeapullrequest.com](http://makeapullrequest.com)? Please include tests :+1:
