### ISSUE TITLE
Changing Unable to Find Config Log Level

### ISSUE THREAD

**Issue by tim-mcgee** [kentcdodds/p-s#14]
Scripts file (or at least the relevant bits):

https://github.com/kentcdodds/p-s/blob/master/bin/p-s.js#L60

The output:

```console
Unable to find config at /Users/konstantinpschera/Development/Projects/ps/package-scripts.js https://github.com/kentcdodds/p-s/blob/v0.0.0-semantically-released/other/ERRORS_AND_WARNINGS.md#unable-to-find-config
Unable to find config at /Users/konstantinpschera/Development/Projects/ps/package-scripts.js https://github.com/kentcdodds/p-s/blob/v0.0.0-semantically-released/other/ERRORS_AND_WARNINGS.md#unable-to-find-config
Scripts must resolve to strings. There is no script that can be resolved from "echo" https://github.com/kentcdodds/p-s/blob/v0.0.0-semantically-released/other/ERRORS_AND_WARNINGS.md#missing-script
```

Problem description:
Every time the config couldn't be loaded the scripts are always not working.

Suggested solution:
Rise the log level to error so p-s gets terminated earlier.

**Comment by kentcdodds** [comment]
> Rise the log level to error so p-s gets terminated earlier.

Your PR raised the log level, but doesn't terminate `p-s`, if you want to do that, you'll need to create another PR.

**Comment by tim-mcgee** [comment]
I think it's something that's useful so I will create one.
