### ISSUE TITLE
Running the coverage in p-s reports package-scripts.js

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#17]
When I run my test command in p-s instead of npm scripts, the file `package-scripts.js` is displayed in my report, even if it's not part of the pattern glob of mocha.

- `p-s` version: 0.9.0
- `node` version: 6.2.0
- `npm` version: 3.8.9

The command executed:

```console
p-s executing: nyc --reporter=text --reporter=lcov p-s test.suite
p-s executing: cross-env NODE_PATH=./src mocha "./test/**/*.spec.js" --compilers js:babel-register -r ./test/helper
```

The issue seems to be located when executing the second command. Because during the first command, if I changed `p-s test.suite` for `npm run test.suite` (my old command), the output is different and the file disappears from the coverage.

**Comment by kentcdodds** [comment]
Hmmm, yeah, I'm not sure how to get around this. The fact of the matter is that were requiring that file, so `nyc` will instrument it for coverage. You'll have to exclude it yourself I'm afraid. Unless you can think of a way around this... PRs welcome.

**Comment by tleunen** [comment]
Indeed, excluding the file will work. I thought there would be another way inside nyc to fix it but I have no clue to get around it :/ So I'll exclude the file, thanks.
