### ISSUE TITLE
Not all scripts are displayed in help

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#18]
- `p-s` version: 0.9.0
- `node` version: 6.2.0

Looks like not all scripts are displayed in the help section. I'm almost sure it's because the process ends before displaying everything.

It seems to be related to Node 6 though because the issue doesn't exist in Node 5.

**Comment by kentcdodds** [comment]
Could you verify your `p-s` version? Did you mean 0.9.0?

**Comment by tleunen** [comment]
yes sorry, I meant 0.9.0 :) (Fixed the original post)

**Comment by kentcdodds** [comment]
I thought I'd fixed that. Thanks for bringing it up. Would you be interested in investigating the problem?

**Comment by tleunen** [comment]
This is not an easy one, because the issue only occurs with Node 6 :/

**Comment by tleunen** [comment]
See https://github.com/tj/commander.js/issues/530
