### ISSUE TITLE
Nested taks are not displayed properly in the help

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#19]
Inside the help section, the task list may be wrong.

If I have a few nested tasks, like:
```
build: {
  x: {
    y: {
      description: "build X-Y",
      script: "do sth"
    }
  }
}
```
With this example, it only display `x.y - build X-Y - do sth`

**Comment by kentcdodds** [comment]
Would you be interested in investigating the problem and proposing a solution? The function in question is implemented [here](https://github.com/kentcdodds/p-s/blob/master/src/bin-utils.js#L106-L146) and tested [here](https://github.com/kentcdodds/p-s/blob/master/src/bin-utils.test.js#L88-L129).
