### ISSUE TITLE
Parallel taks are forwarded to the end command

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#26]
ERROR in multi main
Module not found: Error: Cannot resolve module 'build.test,build.staging,build.edge'

- `p-s` version: 1.0.2
- `node` version: 6.6.1

The command executed:

```console
npm start -p build.x,build.y
```

The output:

```console
ERROR in multi main
Module not found: Error: Cannot resolve module 'build.x,build.y'
```

Problem description:
My build command run webpack to build a bundle file for my project. But when running `npm start -p build.x,build.y`, it appends the parallel commands to webpack and produce an error:
```console
webpack 'build.x,build.y'
```

I think the parallel taks shouldn't be forwarded to the end command

**Comment by kentcdodds** [comment]
Thanks for the report!

Hmmm... Very interesting. If you'd like to dig, [here's](https://github.com/kentcdodds/p-s/blob/367f2747491d15fa5c89633d29fa1e163bd0d138/src/bin-utils.js#L59-L70) where we exclude p-s flags from the args that are forwarded on to the scripts.

**Comment by tleunen** [comment]
Thanks, I'll take a look :)

**Comment by tleunen** [comment]
@kentcdodds When running `npm start -p this,that`. `program.parallel` is undefined in `getScriptsAndArgs`.

**Comment by tleunen** [comment]
Oh I see...

`npm start -p this,that` is executing `p-s "this,that"`.. So the parallel option is gone. I guess npm takes it as an option instead of p-s :/

So I'm now using `npm start -- -p this,that` which resolve the issue.

Closing the ticket, unless you know of a "fix"?

**Comment by kentcdodds** [comment]
Ah, yep, that's the solution. Do you think we could/should add something to the docs as a common pitfall?

**Comment by tleunen** [comment]
Might be useful to add a note for it when using `npm start` instead of `p-s`. In my case, I'm using `npm start` because it's part of a build system. And using `p-s` is not possible. Using `./node-modules/.bin/p-s` fails to run sub-commands because `p-s` is not found.

**Comment by kentcdodds** [comment]
> Might be useful to add a note for it when using npm start instead of p-s. In my case, I'm using npm start because it's part of a build system

Actually, the recommended use is to use `npm start`, but to put the scripts to be run in `package-scripts.json`. So generally you'd put the script you're trying to run in the `package-scripts.json` like [this](https://github.com/kentcdodds/p-s/blob/367f2747491d15fa5c89633d29fa1e163bd0d138/package-scripts.js#L43). Also, I think the thing that caused confusion is a fundamental misunderstanding of how npm scripts work. So maybe documenting something to remind people that if you want to make sure to pass arguments to a script, you need to use `--`. That's what I was thinking.

> And using p-s is not possible. Using ./node-modules/.bin/p-s fails to run sub-commands because p-s is not found.

I think you have a typo. `node-modules` should be `node_modules`. You should be able to run `node_modules/.bin/p-s`. But really, you should be just using `p-s` in [an npm script](https://github.com/kentcdodds/p-s/blob/367f2747491d15fa5c89633d29fa1e163bd0d138/package.json#L7) and it will work fine.

**Comment by tleunen** [comment]
Oh I see, you mean having a simple script which will run my tasks in parallel. Yep I could do that too.


And yes, sorry for the typo. What I mean though was that if I manually run `./node_modules/.bin/p-s this` and then `this` also run `p-s that`, the second command fails because p-s is not available. But that's expected I guess ;)

**Comment by kentcdodds** [comment]
Ah, I see what you're saying. Yeah, basically the way that `p-s` works is it spawns a script with the same `process.env` as the current environment. So if the currently `PATH` doesn't include `node_modules/.bin` then the spawned script wont have it either. I suppose that `p-s` could explicitly add `node_modules/.bin` to the `PATH`. I'll create an issue for discussion about that.
