### ISSUE TITLE
p-s autocomplete in zsh

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#28]
I'm using [prezto](https://github.com/sorin-ionescu/prezto) and it has an autocomplete for `npm run` commands. It would be great to have the same for `p-s` or `npm start` when p-s is used.

Does someone has some experiences writing something like that? :)

**Comment by kentcdodds** [comment]
I don't have experience with this, but it'd be totally awesome to get this! Might be a bit tough because technically the scripts can be dynamic. But should be doable for most use cases.

**Comment by SamVerschueren** [comment]
[Omelette](https://nmotw.in/omelette/) might be able to do that.

**Comment by tleunen** [comment]
Because commands have to start with `npm start`, I'm not sure if we could use omelette to bind the auto completion on `npm` since users might already have an auto completion feature for npm :s

**Comment by kentcdodds** [comment]
Hmmm, maybe soo :-(

**Comment by tleunen** [comment]
I have been thinking about this recently and I believe there's no real solution.

Because we use `npm start xxxx`, we should have a way to dynamically populate the autocomplete for `npm`, but this is already done by `npm` itself so we can't do that afaik.

If `p-s` is installed globally, this should be possible though. We can create a `p-s --autocomplete` that will return the list of available commands, and then add them in the autocomplete module of bash for example. But, this will require to use p-s globally, which is/was not the goal of this lib I guess.

So.. Unless we do a 100% mapping between p-s and npm, I don't think it's really possible with the current state of p-s.
```json
{
  "scripts": {
    "start": "p-s",
    "test": "p-s test",
    "task1": "p-s task1",
    "task2": "p-s task2"
  }
}
```

But we could still have a global `ps-cli` that forward the commands on the local `p-s` instead... But typing `p-s` is quite painful so having a better name without dash would be great for that.

**Comment by kentcdodds** [comment]
We could easily create a `ps` global :) I'm thinking it'd be best as a separate package called `ps-autocomplete` or something and it'd install a `ps` binary which people could use. I think this would be awesome 👍

**Comment by tleunen** [comment]
The thing is... We can't use `ps`. It's already used for the `process status` :/

**Comment by kentcdodds** [comment]
doh!

[TwtXMS5EnKDBK](https://camo.githubusercontent.com/36ac409811395a45ea5a23fbf6c2a61ebbeafb68/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f547774584d5335456e4b44424b2f67697068792e676966>)

How about `nps`...?

**Comment by tleunen** [comment]
Could do the job I think. I don't know anything that already uses `nps` ;-)

**Comment by kentcdodds** [comment]
Dah! I forgot to make a PR for this, but [it was pretty small](https://github.com/kentcdodds/p-s/commit/f01ab0d29c706be7860a077dd896583ff3c29cf5). This is only the first phase. I think we can actually use omelette for this now. I'm going to work on it now.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this one. Please file new issues if you have trouble with `p-s completion`
