### ISSUE TITLE
Default root script

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#33]
Would you be willing to allow a default root script in order to be able to run the script with just `npm start`, or `p-s`?

```js
module.exports = {
    scripts: {
        default: {
            script: 'echo default script'
        }
    }
}
```

**Comment by kentcdodds** [comment]
I could see that being valuable. In that scenario, how do you propose to show the `help`?

**Comment by kentcdodds** [comment]
Yeah, I agree that this would be a good thing to add. Let's do it as you've said :+1:

1. If there is no `default` script, then show help
2. If there's a `default` script, then run that (don't show help)
3. If someone provides `--help` (only) then don't run any scripts and just show help (this means that `npm start foo -- --help` would not log help and run `foo`).

Sound good?

**Comment by kentcdodds** [comment]
Because this is a breaking change, whoever makes the PR for this feature, please make it to the [`next` branch](https://github.com/kentcdodds/p-s/tree/next) so we can get a few breaking changes in a single release.

**Comment by nkbt** [comment]
Good idea
