### ISSUE TITLE
Callback called more then once in Appveyor builds

### ISSUE THREAD

**Issue by nkbt** [kentcdodds/p-s#40]
- `p-s` version: 2.0.0, 2.0.1, 2.0.2
- `node` version: 5.2.0
- `npm` version: 3.3.12

Scripts file (or at least the relevant bits):

```javascript
no js
```

The command executed:

```console
argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--parallel" "build.lib,build.dist,build.min"
```

The output:

```console
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\react-text-filter\npm-debug.log
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "prepublish"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-text-filter@2.1.0 start: `p-s --config react-component-template/package-scripts -s "prepublish"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-text-filter@2.1.0 start script 'p-s --config react-component-template/package-scripts -s "prepublish"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-text-filter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     p-s --config react-component-template/package-scripts -s "prepublish"
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-text-filter
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\react-text-filter\npm-debug.log
Command exited with code 1
```

Problem description:
^ error

Suggested solution:
Have not debugged that yet
See https://ci.appveyor.com/project/nkbt/react-text-filter/build/14

**Comment by nkbt** [comment]
greenkeeper + CI === ❤️

**Comment by kentcdodds** [comment]
Let me know if there's something I can do to help you debug this.

**Comment by nkbt** [comment]
I'll debug it today at home on my Win machine, will see how it goes. Since `react-component-template` had green build there is something to do with running `p-s` with config from `node_modules/react-component-template` (failed on all projects that depend on my template)

**Comment by nkbt** [comment]
I reckon it could be something to do with `find-up`

**Comment by nkbt** [comment]
I found what the issue was, fixed my `react-component-template`. It is strange really, worked fine before as far as I know...

https://github.com/nkbt/react-component-template/commit/b9818256a72a74738fc5c7fb3d960026d0cbd205

That was the change.

**Comment by kentcdodds** [comment]
Huh... Quite odd. I'm not certain why that change would be necessary :-( I wish there were at least some caveat we could add in the README or something....

**Comment by nkbt** [comment]
Yeah, have no idea. It is quite an edge case, no need to add anything to readme.
