### ISSUE TITLE
Filter the help list?

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#41]
Would it be a good idea to have a way to filter the help list, like listing only the scripts which contains a description, or adding a flag "private" and filter them out?

I don't know if it's the right way to do it, but I have a few tasks without description because I treat them as "private", so the developer is not supposed to directly run them.

**Comment by kentcdodds** [comment]
I think I'd be ok to allow a `private: true` property on script objects. 👍

**Comment by kentcdodds** [comment]
I'm thinking that it'd be better for this to be more explicit. Rather than `private`, I think `hideFromHelp` would be better. Thoughts? 💭

**Comment by tleunen** [comment]
To be honest, I don't really know what would be the best way.
Having a way to hide them from the help because "you should not use it" is nice.
But should it be also removed from the "list of tasks" we can trigger? In other term, should it be just hidden or really "private" in a sense it's impossible to trigger it outside of the internal p-s?

As an example, I have a task to copy files. The main copy task is a combination of 2 other tasks but it wouldn't make sense to trigger one of these specific tasks so these ones could be "hidden" and "private".

Not sure if I'm the only one who have this kind of tasks... :/ But my help section si getting really really big, and most of them are just useless for the user anyway.

**Comment by kentcdodds** [comment]
Hmmm... I feel like doing what you're suggesting would overcomplicate `p-s`. I really want to avoid making it overly complex. The more people have to learn about `p-s`-specific behavior, the less happy I'll be.

I'm willing to have a `hidden` property. I think that's pretty straightforward. But anything else is probably too much...

You might consider composing your scripts a little differently. Share these "private" scripts via string concatenation:

```javascript
const copy = 'cpy favicon.ico dist'
module.exports = {
  scripts: {
    build: `do-thing && ${copy}`,
    dev: `do-other-thing && ${copy}`,
  }
}
```

**Comment by tleunen** [comment]
But then you loose the parallelism.

But I agree, having just a `hiddenFromHelp` field would already be a lot better to avoid complicating the lib :)

**Comment by kentcdodds** [comment]
> But then you loose the parallelism.

Very good point. I think that `hiddenFromHelp` is the most I want to do at this point. Alternatively, you could create a separate, parameterized script that does the stuff in parallel (and you could open source that and use it with `p-s`). I think we can agree that we've bumped into the edge of the scope of `p-s` :)

**Comment by kentcdodds** [comment]
To be clear, I'm good to accept a PR that adds a `hiddenFromHelp` property to a script object as discussed. 👍

**Comment by kentcdodds** [comment]
Woot! Thanks @sxn. Hopefully this helps clear things up for you @tleunen :)

**Comment by tleunen** [comment]
Awesome, thanks @sxn :)
