### ISSUE TITLE
Feat: Run multiple scripts in series

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/p-s#42]
As indicated on the [ROADMAP.md](https://github.com/kentcdodds/p-s/blob/5efa68bcf61513d2751200854e7c7643fb84a31a/other/ROADMAP.md) under "Want to do":

> Add the ability to specify multiple scripts that run in series (right now the solution is to just &&)

Let's implement that. I'm going to work on it right now.

**Comment by tleunen** [comment]
How do you plan to do it?
Currently, I'm using an array with a join to keep it "clean".
Like this:
```js
[
  'p-s task1',
  'p-s task2',
  'p-s task3'
].join(' && ')
```

**Comment by kentcdodds** [comment]
Nice solution! I was planning on just doing the same thing we do with `parallel`:

parallel:

```javascript
p-s --parallel foo,bar,baz
```

series:

```javascript
p-s foo,bar,baz
```

**Comment by tleunen** [comment]
Yep, so if one of the task is not a "p-s" task, my array would still be required ;) But this is still a nice addition to match the current parallel "api"!

So doing something like this: 
```js
[
  'p-s clean,clean',
  'webpack'
].join(' && ');
```

**Comment by tleunen** [comment]
Unless we set everything as a p-s task, but then it comes back to the other thread where having "private" tasks could also be a nice addition then :p

**Comment by kentcdodds** [comment]
;-)

**Comment by kentcdodds** [comment]
Whoops! Just realized I didn't make a PR for this one. I would have liked you to review it @tleunen. Do you mind looking at [the commit](https://github.com/kentcdodds/p-s/commit/715f7405455daa88ad80e37b5ca788097fbd2f2e)? I can fix stuff if you feel like it could be improved.

**Comment by tleunen** [comment]
Looks fine to me ;)

**Comment by Hypercubed** [comment]
I know this is closed (and feel like we may have discussed the before :) ) but have you considered that if a script name resolves to an array instead of a string runs the commands in series?

For example instead of:

```js
module.exports = {
  scripts: {
    validate: npsUtils.series('nps build', 'eslint', 'jest')
  }
}
```

we could do:

```js
module.exports = {
  scripts: {
    validate: ['nps build', 'eslint', 'jest']
  }
}
```

or in YAML:

```yml
scripts:
  validate:
    - nps build
    - eslint
    - jest
```

That's what I did in https://github.com/Hypercubed/npsl which I would like to deprecate in favor of nps.

**Comment by kentcdodds** [comment]
Is there a reason that this wont work for you?

```javascript
module.exports = {
  scripts: {
    validate: ['nps build', 'eslint', 'jest'].join(' && ')
  }
}
```

**Comment by kentcdodds** [comment]
Is that sufficient? I just feel like this package is already too magical and think it'd be better to avoid more magic.

**Comment by Hypercubed** [comment]
Yeah, the multiline strings work for me.  Thanks!
