### ISSUE TITLE
This project doesn't solve any problems

### ISSUE THREAD

**Issue by AlicanC** [kentcdodds/p-s#44]
Compare these two examples:
```json
{
  "scripts": {
    "start": "node index.js",
    "lint": "eslint .",
    "test": "ava",
    "test:watch": "ava -w",
    "build": "webpack",
    "build:prod": "webpack -p",
    "validate": "npm-run-all -p -r lint test build"
  }
}
```

```javascript
module.exports = {
  scripts: {
    default: 'node index.js',
    lint: 'eslint .',
    test: {
      default: 'ava',
      watch: {
        script: 'ava -w',
        description: 'run in the amazingly intelligent AVA watch mode'
      }
    },
    build: {
      default: 'webpack',
      prod: 'webpack -p',
    },
    validate: 'p-s --parallel lint,test,build',
  },
}
```

While p-s is supposed to help, it actually introduces more bloat by adding another file with a lot more lines and the configuration is hardly maintainable.

If you Flow-typed the configuration it would look something like this:
```javascript
/* @flow */

declare type StringScript = string;
declare type DescribedScript = {
  script: StringScript,
  description?: string,
};
declare type ScriptNest = {
  default: StringScript | DescribedScript,
  [key: string]: StringScript | DescribedScript | ScriptNest,
};
declare type Config = {
  scripts: ScriptNest,
  options?: {
    silence?: boolean,
  },
};

declare export default Config;
```

You can tell that it will be hard to maintain by the type of `ScriptNest`. Values of it's properties can be any of the three types which will be absolutely indistinguishable in a large configuration. Configuration formats like this are doomed to become a thousand-piece puzzle.

---

There is the description functionality, but describing scripts like `"test:watch": "ava -w"` as "Run AVA in watch mode." is absolutely unnecessary. Most scripts are already self-explanatory or can be made self-explanatory by using long forms of arguments. (Bad: `ava -w` Good: `ava --watch`)

The "unmaintainable mess" example in the README.md is a bad example. You can maintain a large `scripts` without any problems if you follow a few rules:

```javascript
{
  "scripts": {
    "start": "node server.prod.js",

    "start-dev": "babel-node server.dev.js",

    "clean": "rimraf dist",

    "build": "npm run clean && npm run build:webpack",
    "build:webpack": "webpack --config webpack.config.prod.babel.js",
    
    "test": "npm run test:eslint && npm run test:flow",
    "test:eslint": "eslint \"src/**/*.js\"",
    "test:flow": "flow; test $? -eq 0 -o $? -eq 2"
  }
}
```

The result of `npm run` for those scripts will be:
```
Lifecycle scripts included in app:
  start
    node server.prod.js
  test
    npm run test:lint && npm run test:flow

available via `npm run-script`:
  start-dev
    babel-node server.dev.js
  clean
    rimraf dist
  build
    npm run clean && npm run build:webpack
  build:webpack
    webpack --config webpack.config.prod.babel.js
  test:flow
    flow; test $? -eq 0 -o $? -eq 2
  test:lint
    eslint "src/**/*.js"
```

As you can see, all scripts can be easily listed and understood. Since task and step names are colon separated, it is easy to see what is a task and what is a step. With steps, if one of your tasks fail, you can run the failed step solo to debug easily.

If you end up with too much steps, you can hack in a creative script that removes steps from `npm run` output:
```
"list": "npm run | sed -e '/^  [^ ]*:.*$/,/^/d'"
```

Descriptions were also suggested for npm's core and decided unworthy of complexity for the same reasons: https://github.com/npm/npm/issues/9952

---

Another problem is the way "prefixing" is advertised. It is surprisingly used in the actual configuration in the intro video. There is seriously no way you can properly maintain a line like `p-s --parallel b.m,b.u,b.u.m` in your configuration.

You also can't safely use it in a shell. `npm start b.u.m` can refer to `build.umd.min` in one commit and `break.user.machine` in another. That's why these are never dynamically generated in CLIs and always hardcoded.

**Comment by tleunen** [comment]
Just because `p-s` allows to have a description, it's already a problem solver for me.

When you have a project with a lot of tasks, and then a new person joins your team, having a description is really good to quickly explain the reason of a task and what it does without reading the scripts.

**Comment by AlicanC** [comment]
@tleunen interesting. I guess we are lucky that no newcomers in our company needed such help (or maybe our scripts are simple and don't even count). Could you point me to a project where p-s really shines as a tool that helps newcomers? I really want to understand your situation since I am the guy who introduces people to JS stuff in my company.

Could you also share some thoughts on the other two problems I have mentioned?

Thought I can't remember which projects they were, I do remember that suggestions similar to your prefixing being rejected in a few CLI projects for the reasons I have mentioned. Do you also see this as a feature that allows bad practices or do you disagree?

How about the shape of the configuration? Wouldn't you rather a flat configuration like npm's?

**Comment by kentcdodds** [comment]
I've updated the video with an annotation indicating that you shouldn't actually use the aliases in your `package-scripts.js` configuration. I agree with you that it's better to be hard coded and only really used when you're running scripts yourself.

As for everything else you talked about, feel free to disagree and not use this project. But please don't be rude. Just because you don't think it's useful doesn't mean you have to file an issue to show how much you think the project is useless. Just move on.

**Comment by nkbt** [comment]
Tis is the funniest Issue I've seen so far.
Much ❤️
