### ISSUE TITLE
Should p-s stop executing commands when an error occurs?

### ISSUE THREAD

**Issue by tleunen** [kentcdodds/p-s#48]
I wonder if p-s should stop the execution when an error occurs when executing multiple commands (in parallel or not).

Any thoughts?

Especially when p-s run a command and then the second command depends on the first one...

**Comment by kentcdodds** [comment]
Yes it should. I thought about this just recently. I'm happy to accept a pull request to do this!

**Comment by kentcdodds** [comment]
I think I'd like to get [this](https://github.com/mysticatea/npm-run-all/issues/59) done before working on this.
