### ISSUE TITLE
Also support function

### ISSUE THREAD

**Issue by rwu823** [kentcdodds/p-s#6]
currently
```js
module.exports = {
  scripts: {
    build: 'babel-node scripts/build'
  }
}
```
expect to support as well:

```js
module.exports = {
  scripts: {
    build(){
      return  'babel-node scripts/build'
    }
  }
}
```

**Comment by kentcdodds** [comment]
Cool. Can you explain a use case for doing this?

**Comment by rwu823** [comment]
Sometimes we need to do more complex in function, just gets more flexible.

e.g.  Inject env variable
```js
module.exports = {
  scripts: {
    build: {
      default: {
        script() {
          return  'babel-node scripts/build'    
        }
      },

      dev() {
        process.env.BUILD = {isDev: true}
        return  'babel-node scripts/build'
      }

      prod() {
        process.env.BUILD = {isProd: true}
        return  'babel-node scripts/build'
      }      
    }
  }
}
```

in `build.js`

```js
const {isDev, isProd} = process.env.BUILD
```

**Comment by kentcdodds** [comment]
Ah, I see, here are two workarounds for you:

```javascript
module.exports = {
  scripts: {
    build: {
      default: 'babel-node scripts/build',
      dev: 'cross-env NODE_ENV=development babel-node scripts/build',
      prod: 'cross-env NODE_ENV=production babel-node scripts/build',
    }
  }
}
```

Then in `build.js`

```javascript
const isDev = process.env.NODE_ENV === 'development'
const isProd = process.env.NODE_ENV === 'production'
```

Note: It's more common to use the `NODE_ENV` environment variable for things like this, but you could do something similar with a `BUILD` variable.

---

Or:

```javascript
module.exports = function getPackageScripts(input) {
  process.env.BUILD = {isDev: input === 'build.dev', isProd: input === 'build.prod'}
  return {
    scripts: {
      build: {
        default: 'babel-node scripts/build',
        dev: 'babel-node scripts/build',
        prod: 'babel-node scripts/build',
      }
    }
  }
}
```

Let me know if you have any questions or if you feel like the documentation/examples could be updated to explain this use case better.

**Comment by kentcdodds** [comment]
I'm starting to think though that implementing what you're suggesting may be a good idea... Not 100% on board yet. Let me know what you think of my work arounds.

**Comment by rwu823** [comment]
Thanks for reply so soon.

For the example 1:
```js
{
dev: 'cross-env NODE_ENV=development'
}
```
I don't want to do this because `Object` syntax has better structure if in complex case not just exports as a string 

Then the example 2:
Maybe good, is that supporting now?
```js
module.exports = function getPackageScripts(input) { ... }
```

**Comment by kentcdodds** [comment]
I think that it could be helpful to have the functionality you suggest. Feel free to [makeapullrequest.com](http://makeapullrequest.com) :-)

**Comment by sparty02** [comment]
Would a property getter work here?

**Comment by kentcdodds** [comment]
That should work! Let me know! If it does, could you add it to the examples file?

**Comment by rwu823** [comment]
`getter` cannot work for me

**Comment by kentcdodds** [comment]
Well, feel free to [makeapullrequest.com](http://makeapullrequest.com) :-)

**Comment by kentcdodds** [comment]
Hmmm... I've actually decided that this overcomplicates the `p-s` API and I don't want to do that. So I'm going to close this one.
