### ISSUE TITLE
script could support function?

### ISSUE THREAD

**Issue by janryWang** [kentcdodds/p-s#62]
like this
```
{
   stuff:{
       script:function(args){

       }
   }
}

```

**Comment by kentcdodds** [comment]
Hi @janryWang,
That's actually something that I've explicitly called out in [the roadmap](https://github.com/kentcdodds/p-s/blob/master/other/ROADMAP.md) that I wont do:

> Wont Do
> - Allow you to specify an individual script as a function to call rather than spawn a process....

Thanks!

**Comment by janryWang** [comment]
Thx @kentcdodds ,
But , do you have any time schedule?

**Comment by kentcdodds** [comment]
Sorry, to be clear, I will _not_ be adding this feature to `p-s`. Please see the Roadmap for an explanation for why.

**Comment by janryWang** [comment]
Okay. thx
