### ISSUE TITLE
Allow initializing to a YAML file

### ISSUE THREAD

**Issue by sxn** [kentcdodds/p-s#66]
Currently, users who want to start using `p-s` in an existing project can hit the ground running by using `nps init`. This will generate a `package-scripts.js` file from their `package.json` file and update the latter to utilize the `nps` binary.

Since we now have YAML config support (#64), it would be great if `nps init` would allow generating a `package-scripts.yml` file as well.

What about `nps init --type=yaml`?
Feel free to pick it up, otherwise I'll probably be able to do this some time this weekend. 😄

**Comment by kentcdodds** [comment]
That API you're suggesting looks good to me :)

**Comment by bfred-it** [comment]
Given how terse and readable YAML is, would it make sense to make it the default/preferred version? In the docs, in the init and in the default config lookup

**Comment by kentcdodds** [comment]
Yeah, though one of the main reasons I built `p-s` is so I can have dynamic scripts. I'll probably always use the module version personally.

**Comment by sxn** [comment]
While I agree with the readability point, I'm a bit afraid making the YAML version the default would undermine the purpose of the project - for the exact reason that @kentcdodds provided.
