### ISSUE TITLE
Idea: Add pre/post commands

### ISSUE THREAD

**Issue by DavidWells** [kentcdodds/p-s#67]
I miss this from npm scripts =)

What is it was implemented like so?

``` js
// if pre
if(cmd['pre' + cmdName ]) {
 // if matching pre command exists run it
 cmd['pre' + cmdName ]()
} 

// do normal command
cmd[cmdName ]()

// if post
if(cmd['post' + cmdName ]) {
 // if matching post command exists run it
 cmd['post' + cmdName ]()
} 
```

**Comment by kentcdodds** [comment]
One thing I'd be worried about is people would expect things to work the same way that normal lifecycle hooks work (like `install`). So someone may try to make a `prepublish` script expecting it to run when they run `npm publish` but it wouldn't. Any ideas of how to combat that?

**Comment by DavidWells** [comment]
Hmmmm perhaps for odd cases like that we `console.log` a warning if they have one of 'wierd' npm script commands.

`warning 'commandXYZ' won't run like npm scripts. See issue [link to long npm github thread] `

I can't remember which work not how you'd expect. I'm sure you do though =)

**Comment by kentcdodds** [comment]
Hmmm, that could get really annoying. Let's just document it and let people do whatever you want. I'm good to accept a PR for this. The relevant code is [here](https://github.com/kentcdodds/p-s/blob/master/src/index.js#L30) and [here](https://github.com/kentcdodds/p-s/blob/master/src/index.js#L40). I think that we should probably have an intermediary function that we call there which will look up the pre/post scripts for the given script. Here are a few variations of what should work I think:

```javascript
{
  prefoo: 'echo prefoo', // thinking I'd be ok without this one...
  foo: 'echo foo',
  postfoo: 'echo postfoo', // and this one... I think if you want pre/post, make in an object with pre/post. Thoughts?
  bar: {
    pre: 'echo prebar',
    default: 'echo bar',
    post: 'echo postbar',
  },
  baz: {
    default: {
      pre: 'echo prebaz',
      script: 'echo baz',
      post: 'echo postbaz',
    },
    foobar: {
      pre: 'echo prefoobar',
      script: 'echo foobar',
      post: 'echo postfoobar',
    }
  }
}
```

**Comment by rrag** [comment]
@kentcdodds 

> I think if you want pre/post, make in an object with pre/post. Thoughts?

I agree

I want to sign up for this, but here is a change I wish to propose. Thoughts?

```diff
{
    prefoo: 'echo prefoo', // thinking I'd be ok without this one...
    foo: 'echo foo',
    postfoo: 'echo postfoo', // and this one... I think if you want pre/post, make in an object with pre/post. Thoughts?
    bar: {
      pre: 'echo prebar',
-     default: 'echo bar',
+     script: 'echo bar',
      post: 'echo postbar',
    },
    baz: {
      default: {
        pre: 'echo prebaz',
        script: 'echo baz',
        post: 'echo postbaz',
      },
      foobar: {
        pre: 'echo prefoobar',
        script: 'echo foobar',
        post: 'echo postfoobar',
      },
    },
  }
```

**Comment by kentcdodds** [comment]
We've decided to not do this. See #83 for more info.
