### ISSUE TITLE
Move to yargs

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/p-s#70]
Commander is cool and all, but there's some hacky things we have to do to get our CLI to do what we want. It'd be sweet to use [yargs](https://github.com/yargs/yargs) which is much more flexible.

All changes should happen in [here](https://github.com/kentcdodds/p-s/blob/master/src/bin/nps.js). Should hopefully be able to just use it similar to how I've used it in [split-guide](https://github.com/kentcdodds/split-guide) [here](https://github.com/kentcdodds/split-guide/blob/fb4b2a2ebc1fb8c3c010c2af1318861b8bb1bb13/src/bin/index.js#L6-L30) :+1:

**Comment by sxn** [comment]
That's a pretty solid starting point! 👍 
Some things that should change [here](https://github.com/kentcdodds/p-s/blob/master/src/bin-utils/index.js#L89) as well, from the looks of it, right?

**Comment by kentcdodds** [comment]
Yes, probably so...

**Comment by nkbt** [comment]
I actually found `nomnom` to be the best. Just in case you've never heard of it http://npm.im/nomnom

**Comment by kentcdodds** [comment]
I've never used `nomnom`, but I have used `yargs` and liked it pretty well. It's also much more widely used. I think I'd like to stick with that one personally. What do you think @sxn?

**Comment by sxn** [comment]
Hm. Actually I hadn't played around with either of those, so I can't form an informed opinion. I'll briefly look into both before diving in and come back. Without looking into them I'd probably choose {{yargs}} just because there would be at least one person who knows this codebase *and* the library we'd be introducing. :D
