### ISSUE TITLE
Indent child task descriptions when running help command

### ISSUE THREAD

**Issue by gunnx** [kentcdodds/p-s#73]
- `p-s` version: 3.0.1
- `node` version:  6.9.1
- `npm` version:  3.10.8

Scripts file (or at least the relevant bits):

``` javascript
https://github.com/kentcdodds/p-s/blob/master/src/bin-utils/index.js
```

The command executed:

``` console
./node_modules/p-s/dist/bin/nps.js help
```

The output:

``` console
dev - DEVELOPMENT: Build CSS, build and run server, build, serve and watch client - npm start dev.build-sass,dev.runServerRunClientAndWatchSass
dev.buildServerAndStart - npm start dev.build,start

```

Problem description:
Tasks that are namespaced do not render out indented.

Suggested solution:
Output any nested tasks with spaces to indicate they are children of parent task

**Comment by kentcdodds** [comment]
Hi @gunnx! Thanks for the issue. I'd be good with that! Would you like to [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by gunnx** [comment]
Ok will give it a try!
