### ISSUE TITLE
Hidden scripts error when trying to run

### ISSUE THREAD

**Issue by gunnx** [kentcdodds/p-s#74]
- `p-s` version: 3.0.1
- `node` version:  6.9.1
- `npm` version:  3.10.8

Scripts file (or at least the relevant bits):

``` javascript
https://github.com/kentcdodds/p-s/blob/master/src/resolve-script-object-to-string.js
```

Config extract:

``` javascript
dev: {
    build: {
      description: '',
      script: `NODE_ENV=development webpack --config ${webpackServerConfig}`,
      hiddenFromHelp: true
    },
...
```

The command executed:

``` console
nps dev.build
```

The output:

``` console
....
Scripts must resolve to strings. There is no script that can be resolved from "dev.build" https://github.com/kentcdodds/p-s/blob/v3.0.1/other/ERRORS_AND_WARNINGS.md#missing-script
....
```

Problem description:
Assume that the expected behaviour of flag `hiddenFromHelp` is to only remove it from the help list and not stop you running. 

Suggested solution:
Not sure I fully understand the code but looks like `resolvePlainObjectToScript` is returning `undefined` if the flag is set, though looks like this function is used by help and run tasks.

**Comment by kentcdodds** [comment]
Ah, yes that's definitely a bug. If you'd like to work on a fix, I'd be happy to help you with it. On my phone right now and about to board a plane, but if you need help, I can give you more direction later. Feel free to poke around and check-out CONTRIBUTING.md
