### ISSUE TITLE
nps init should ask if you want to override an existing package-scripts.js

### ISSUE THREAD

**Issue by beeman** [kentcdodds/p-s#86]
First of all thanks for creating this great utility. It makes my work a lot easier :)

- `p-s` version: 3.0.3
- `node` version: v7.2.0
- `npm` version: 3.10.10

Scripts file (or at least the relevant bits):

```javascript
# Any customized script
```

The command executed:

```console
$ nps init
```

The output:

```console
Your scripts have been saved at /private/tmp/p-s-is-awesome/package-scripts.js
Check out your scripts in there. Go ahead and update them and add descriptions to the ones that need it
Your package.json scripts have also been updated. Run `npm start help` for help
You may also want to install the package globally and installing autocomplete script. You can do so by running
  npm install --global p-s
  nps completion <optionally-your-bash-profile-file>
The bash profile file defaults to ~/.bash_profile for bash and ~/.zshrc for zsh
```

Problem description:

When there is an existing `package-scripts.js` in the project the command `nps init` will override it with the defaults. 

I'm not sure if this is by design but if so I think it makes sense to have a confirmation that asks the user for a confirmation to override it. 

Suggested solution:

I think there are generally two solutions to consider:
- Ask for confirmation to override the existing file.
- Skip creating the file when it exists, and inform the user to remove the existing file.

**Comment by kentcdodds** [comment]
This is great. I like the `Ask for confirmation to override the existing file.` option. Potentially, we could also merge the existing file with the new... Could be 3 options.

Feel free to [makeapullrequest.com](http://makeapullrequest.com) :)

**Comment by beeman** [comment]
Thanks for your reply @kentcdodds . I'm well aware how to make a PR, but thanks for the link!

I will give a go at implementing the confirmation. If you like feel free to assign this issue to my name.

**Comment by kentcdodds** [comment]
Haha, yeah, I know you can make a PR. I leave it there in case someone else comes across this issue and wants to implement it. Also, I have it on autocomplete ;-)
