### ISSUE TITLE
/bin-utils loadJSConfig() doesn't support package-scripts.js exporting a function

### ISSUE THREAD

**Issue by erikfox** [kentcdodds/p-s#88]
[`src/get-scripts-from-config.js`](https://github.com/kentcdodds/p-s/blob/master/src/get-scripts-from-config.js#L5) allows `package-scripts.js` to export a function:
```js
import {isPlainObject, isFunction} from 'lodash'

export default getScriptsFromConfig

function getScriptsFromConfig(scripts, input) {
  if (isPlainObject(scripts)) {
    return scripts
  } else if (isFunction(scripts)) {
    return scripts(input)
  }
  return {}
}
```

but [`src/bin-utils/index.js loadJSConfig()`](https://github.com/kentcdodds/p-s/blob/master/src/bin-utils/index.js#L28) does not:
```js
const loadJSConfig = getAttemptModuleRequireFn(function onFail(configPath, requirePath) {
  log.error({
    message: colors.red(`Unable to find JS config at "${configPath}". Attempted to require as "${requirePath}"`),
    ref: 'unable-to-find-config',
  })
  return undefined
})

...

function loadConfig(configPath) {
  if (configPath.endsWith('.yml')) {
    return loadYAMLConfig(configPath)
  }

  return loadJSConfig(configPath)
}
```

So when attempting to run a `default` script via command line, you get the generic help output with a "no scripts" warning:
```js
// package-scripts.js
exports.scripts = function (input) { ... }
```
```bash
$ nps

  Usage: nps [options]

  Options:

    -h, --help                                  output usage information
    -V, --version                               output the version number
    -s, --silent                                Silent nps output
    -p, --parallel <script-name1,script-name2>  Scripts to run in parallel (comma seprated)
    -c, --config <filepath>                     Config file to use (defaults to nearest package-scripts.yml or package-scripts.js)
    -l, --log-level <level>                     The log level to use (error, warn, info [default])
    -r, --require <module>                      Module to preload

There are no scripts available
```

**Comment by kentcdodds** [comment]
Hmmm... I'm not sure I see where the problem is specifically. Do you have a proposed solution? May be easier to understand what's going on if I see a diff for the fixed version.

**Comment by erikfox** [comment]
@kentcdodds I would like to see the binaries  [determine whether the config is `isPlainObject()` or `isFunction()`](https://github.com/kentcdodds/p-s/blob/master/src/get-scripts-from-config.js#L5) and evaluate if `isFunction() === true` before returning as part of [`getPSConfig()`](https://github.com/kentcdodds/p-s/blob/master/src/bin/nps.js#L70) flow.

That way, 
1. when you run `nps` or `nps default`, the evaluated default function will run
2. when you run `nps --help`, the evaluated functions will be listed

**Comment by erikfox** [comment]
If that makes sense, I don't mind writing implementation.

**Comment by kentcdodds** [comment]
Give it a go, I look forward to seeing the implementation :) And don't forget to check [the contributing guidelines](https://github.com/kentcdodds/p-s/blob/master/CONTRIBUTING.md)!
