### ISSUE TITLE
Error thrown if "scripts" property missing from package.json

### ISSUE THREAD

**Issue by gunnx** [kentcdodds/p-s#89]
- `p-s` version: 3.0.3
- `node` version: 7.4.0
- `npm` version: 4.0.5

Scripts file (or at least the relevant bits):

```javascript
/p-s/dist/bin-utils/initialize/index.js
```

The command executed:

```console
./node_modules/.bin/p-s- init
```

The output:

```console
./node_modules/p-s/dist/bin-utils/initialize/index.js:31
   test: scripts.test ? 'nps test' : undefined
                 ^

TypeError: Cannot read property 'test' of undefined
```

Problem description:
Init fails to work if there is no "scripts" object in package.json

Suggested solution:
Inform user of problem or create "scripts" property automatically.

**Comment by kentcdodds** [comment]
Yeah, let's create the scripts automatically. Want to make a pull request?
