### ISSUE TITLE
Link on NPM broken

### ISSUE THREAD

**Issue by Ryuno-Ki** [kentcdodds/p-s#96]
Problem description:

https://www.npmjs.com/package/npm-package-scripts lists https://github.com/kentcdodds/nps as path to source.

Suggested solution:

Update link to https://github.com/kentcdodds/p-s

**Comment by kentcdodds** [comment]
Hi @Ryuno-Ki,
Thanks for the report. I should probably deprecate that package. I was going to rename this package and decided not to anymore. The actual npm package is: https://www.npmjs.com/package/p-s
